{% set version = '1.0.1' %}

package:
  name: r-kableextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kableExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kableExtra/kableExtra_{{ version }}.tar.gz
  sha256: 95d3e1175183a791b2f0cc6582ae324483eaaae50f75b1bb7b262c0541e35e6f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-digest
    - r-glue
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-webshot
    - r-xml2 >=1.1.1
  run:
    - r-base
    - r-digest
    - r-glue
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-webshot
    - r-xml2 >=1.1.1

test:
  commands:
    - $R -e "library('kableExtra')"           # [not win]
    - "\"%R%\" -e \"library('kableExtra')\""  # [win]

about:
  home: http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra
  license: MIT
  summary: 'Build complex HTML or ''LaTeX'' tables using ''kable()'' from ''knitr''  and the
    piping syntax from ''magrittr''. Function ''kable()'' is a light weight  table generator
    coming from ''knitr''. This package simplifies the way to  manipulate the HTML or
    ''LaTeX'' codes generated by ''kable()'' and allows  users to construct complex
    tables and customize styles using a readable  syntax. '
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - PertuyF
