{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-kableextra
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/kableExtra_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/kableExtra/kableExtra_{{ version }}.tar.gz
  sha256: 3ab6d4cf6ead689c57f9edd2aa8fd05ebc260443ddb42c4c9bfbeacbfff14558

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-digest
    - r-glue
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-webshot
    - r-xml2 >=1.1.1
  run:
    - r-base
    - r-digest
    - r-glue
    - r-htmltools
    - r-knitr >=1.16
    - r-magrittr
    - r-readr
    - r-rmarkdown >=1.6.0
    - r-rstudioapi
    - r-rvest
    - r-scales
    - r-stringr >=1.0
    - r-viridislite
    - r-webshot
    - r-xml2 >=1.1.1

test:
  commands:
    - $R -e "library('kableExtra')"           # [not win]
    - "\"%R%\" -e \"library('kableExtra')\""  # [win]

about:
  home: http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra
  license: MIT
  summary: "Build complex HTML or 'LaTeX' tables using 'kable()' from 'knitr'  and the piping syntax from 'magrittr'. Function 'kable()' is a light weight  table generator coming from 'knitr'. This package simplifies the way to  manipulate the HTML or 'LaTeX' codes generated by 'kable()' and allows  users to construct complex\
    \ tables and customize styles using a readable  syntax. "
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
    - PertuyF

# Package: kableExtra
# Type: Package
# Title: Construct Complex Table with 'kable' and Pipe Syntax
# Version: 1.0.1
# Authors@R: c( person('Hao', 'Zhu', email = 'haozhu233@gmail.com', role = c('aut', 'cre'), comment = c(ORCID = '0000-0002-3386-6076')), person('Thomas', 'Travison', role = 'ctb'), person('Timothy', 'Tsai', role = 'ctb'), person('Will', 'Beasley', email = 'wibeasley@hotmail.com', role = 'ctb'), person('Yihui', 'Xie', email = 'xie@yihui.name', role = 'ctb'), person('GuangChuang', 'Yu', email = 'guangchuangyu@gmail.com', role = 'ctb'), person('Stephane', 'Laurent', role = 'ctb'), person('Rob', 'Shepherd', role = 'ctb'), person('Yoni', 'Sidi', role = 'ctb'),  person('Brian', 'Salzer', role = 'ctb'), person('George', 'Gui', role = 'ctb'), person('Yeliang', 'Fan', role = 'ctb'), person('Duncan', 'Murdoch', role = 'ctb') )
# Description: Build complex HTML or 'LaTeX' tables using 'kable()' from 'knitr'  and the piping syntax from 'magrittr'. Function 'kable()' is a light weight  table generator coming from 'knitr'. This package simplifies the way to  manipulate the HTML or 'LaTeX' codes generated by 'kable()' and allows  users to construct complex tables and customize styles using a readable  syntax.
# License: MIT + file LICENSE
# LazyData: TRUE
# URL: http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra
# BugReports: https://github.com/haozhu233/kableExtra/issues
# Depends: R (>= 3.1.0)
# Imports: knitr (>= 1.16), magrittr, stringr (>= 1.0), xml2 (>= 1.1.1), rvest, rmarkdown (>= 1.6.0), readr, scales, viridisLite, stats, grDevices, htmltools, rstudioapi, glue, tools, webshot, digest
# Suggests: testthat, magick, formattable, dplyr
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-01-22 08:01:16 UTC; haozhu
# Author: Hao Zhu [aut, cre] (<https://orcid.org/0000-0002-3386-6076>), Thomas Travison [ctb], Timothy Tsai [ctb], Will Beasley [ctb], Yihui Xie [ctb], GuangChuang Yu [ctb], Stephane Laurent [ctb], Rob Shepherd [ctb], Yoni Sidi [ctb], Brian Salzer [ctb], George Gui [ctb], Yeliang Fan [ctb], Duncan Murdoch [ctb]
# Maintainer: Hao Zhu <haozhu233@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-01-22 09:00:03 UTC
